<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@1.0.1 castle-prod.glb -T -S
-->

<script>
  import { Group } from 'three'
  import { T, forwardEventHandlers } from '@threlte/core'
  import { useGltf } from '@threlte/extras'

  export const ref = new Group()

  const gltf = useGltf('/castle-prod-transformed.glb', { useDraco: true })

  const component = forwardEventHandlers()
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T.Group position={[0, 0, 0]}>
      <T.Mesh geometry={gltf.nodes.Plane002.geometry} material={gltf.materials.wall_1} />
      <T.Mesh geometry={gltf.nodes.Plane002_1.geometry} material={gltf.materials.roof_1} />
    </T.Group>
    <T.Mesh geometry={gltf.nodes.Cylinder001.geometry} material={gltf.materials.rod} />
    <T.Mesh geometry={gltf.nodes.Cylinder001_1.geometry} material={gltf.materials.orb} />
    <T.Mesh geometry={gltf.nodes.Cylinder002.geometry} material={gltf.materials.rod} />
    <T.Mesh geometry={gltf.nodes.Cylinder002_1.geometry} material={gltf.materials.orb} />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
